--------------------------------------------------------
--  File created - Thursday-August-06-2020   
--------------------------------------------------------
REM INSERTING into IMIGRATION.IM_MENU_MASTER
SET DEFINE OFF;
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (61,1,'APIS Error in Processing','APIS Error in Processing','im_pax_apis_error01.jsp',to_date('02-08-20','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (10,1,'APIS Files Count','APIS Files Count','IM_APIS_FILES_COUNT00.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (9,1,'APIS Table Data Count','APIS Table Data Count (APIS)','IM_APIS_TABLE_COUNT.JSP?TABLE_NAME=IM_APIS',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (62,1,'APIS Table Data Monthly Count','APIS Table Data Monthly Count','{"APIS-PAX": "im_apislog_monthwise_apis_pax_pdf.jsp?rpt_type=1","FLIGHT_ERROR": "im_apislog_monthwise_flight_error_pdf.jsp?rpt_type=1"
}',to_date('02-08-20','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (13,1,'Add PAX to Suspect List','Add PAX to Suspect List','IM_DYNAMIC_ADD_SUSPECT00.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (64,1,'Arrival APIS Statistics','Arrival APIS Statistics','im_apis_arr.jsp',to_date('02-08-20','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (11,1,'Automatic Suspect Passenger List','Automatic Suspect Passenger List','IM_DYNAMIC_SUSPECT_REPORT13.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (12,1,'Automatically Generated Suspect Passengers List','Automatically Generated Suspect Passengers List','IM_DYNAMIC_SUSPECT_REPORT13_ROLE.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (63,1,'Departure APIS Statistics','Departure APIS Statistics','im_apis_dep.jsp',to_date('02-08-20','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (4,1,'Dis-Embarkation Port-Wise Breakup Summary','Dis-Embarkation Port-Wise Breakup Summary','IM_APIS_PORTCOUNT01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (3,1,'Duplicate Records based on Passport No.','Duplicate Records based on Passport No.','IM_APIS_DUPLICATE01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (6,1,'Dynamic Query','Dynamic Query','IM_DYNAMIC_APIS_REPORT01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (2,1,'Inbound Carrier Summary Report','Inbound Carrier Summary Report','IM_APIS_REPORT01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (8,1,'International Flight arriving to India','International Flight arriving to India','IM_APIS_INT_FLIGHTS_PDF.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (1,1,'Status of Processing of APIS Files','Status of Processing of APIS Files','IM_APIS_SERVERFILES01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (5,1,'Summary Report after processing APIS Data','Summary Report after processing APIS Data','IM_APIS_PAX_SUMMARY01.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (7,1,'System Generated Suspect Passenger List','System Generated Suspect Passenger List','IM_DYNAMIC_SUSPECT_REPORT00.JSP',to_date('29-10-14','DD-MM-RR'),'ADMIN');
Insert into IMIGRATION.IM_MENU_MASTER (MENU_ID,MODULE_ID,MENU_NAME,MENU_DESC,TARGET_PAGE,ENTRY_DATE,USER_ID) values (60,1,'User-wise Monthly Usage of CBEC-APIS Application','User-wise Monthly Usage of CBEC-APIS Application','im_monthly_apis_usage01.jsp',to_date('02-08-20','DD-MM-RR'),'ADMIN');
